// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmdJAqSCe9KxKm5ecY9XkmoygS-kfOjgg',
    appId: '1:580219854349:web:127a38f5b0a4ecf3b7bf44',
    messagingSenderId: '580219854349',
    projectId: 'todo-app-test-3a232',
    authDomain: 'todo-app-test-3a232.firebaseapp.com',
    storageBucket: 'todo-app-test-3a232.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvO_Et74lsMIGdriepmKKR5fwJI7TM-Q4',
    appId: '1:580219854349:android:e97811d854d666bdb7bf44',
    messagingSenderId: '580219854349',
    projectId: 'todo-app-test-3a232',
    storageBucket: 'todo-app-test-3a232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCflgBMtLumI2gmhCsLyq7hQ6MnUdDjAzw',
    appId: '1:580219854349:ios:0fa148fcb04d40deb7bf44',
    messagingSenderId: '580219854349',
    projectId: 'todo-app-test-3a232',
    storageBucket: 'todo-app-test-3a232.appspot.com',
    iosBundleId: 'com.example.todoAppTest',
  );
}
